@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/release/2-2/dist/AzureCommon.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/release/2-2/dist/AzureC4Integration.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/release/2-2/dist/Containers/AzureContainerApp.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/release/2-2/dist/Identity/AzureActiveDirectory.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/release/2-2/dist/Storage/AzureBlobStorage.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/release/2-2/dist/DevOps/AzureApplicationInsights.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/release/2-2/dist/Security/AzureKeyVault.puml

LAYOUT_LEFT_RIGHT()

Container_Ext(client, "Client", "Client Application")

AzureContainerApp(auth, "mil-auth", "MIL Authorization Server")
AzureActiveDirectory(entraid, "Authorization Server", "Azure Entra ID")
AzureBlobStorage(storage, "Storage", "Azure Blob Storage")
AzureKeyVault(keyvault, "Key Vault", "Azure Key Vault")
AzureApplicationInsights(appinsights, "OpenTelemetry", "Azure Application Insights")

Rel(client, auth, "uses")
Rel(auth, entraid, "gets access tokens for Azure resources")
Rel(auth, storage, "gets configuration")
Rel(auth, keyvault, "creates keys, gets keys, signs, verifies signatures, encrypts, decrypts")
Rel(auth, appinsights, "sends OpenTelemetry data")
@enduml