@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_LEFT_RIGHT()

Person(admin, "Admin")
Person(maintainer, "Maintainer")

Container_Ext(atm_layer, "ATM Layer")
Container_Ext(3rd_party, "3rd-party Server Application")
Container_Ext(mil_other, "Other MIL Service")

Container(auth, "mil-auth", "")
Container_Ext(entraid, "Authorization Server", "")
Container_Ext(keyvault, "Key Vault", "")
ContainerDb(repo, "Database", "")
Container_Ext(appinsights, "OpenTelemetry", "")

admin --> auth
maintainer --> auth
atm_layer --> auth
3rd_party --> auth
mil_other --> auth
auth --> entraid
auth --> repo
auth --> keyvault
auth --> appinsights

@enduml