@startuml
!include_many init.puml
note over auth #LightPink
	__ $var("access token payload") __
	{
		"sub": "$var("subject")",
		"subjectType": "$var("subject type")",
		"aud": "mil.pagopa.it",
		"clientId": "$var("client id")",
		"fiscalCode": {
			"kid": "$var("enc/dec key my id")",
			"alg": "RSA-OAEP-256",
			"value": "$var("enc fiscal code")"
		},
		"iss": "$var("mil-auth url")",
		"groups": [
			"$var("role #1")",
			"$var("role #2")",
			.
			.
			.
			"$var("role #n")"
		],
		"exp": $var("current unix epoch") + $var("access token duration"),
		"iat": $var("current unix epoch")
	}
end note
@enduml