@startuml
!include_many init.puml

group #LightBlue client credentials validation
	auth -> repo ++ : find("clientId", $var("client id"))
	repo --> auth -- : $var("client")
	!include_many client.puml

	note over auth #Orange
		On client not found, return 401 with specific error body
		On any other error, return 500 with specific error body
	end note
	
	auth -> auth : verify that $var("stored channel") = $var("channel")

	note over auth #Orange
		On verification failure, return 401 with specific error body
	end note

	auth -> auth : verify $var("client secret") against $var("salt") and $var("secret hash")

	note over auth #Orange
		On verification failure, return 401 with specific error body
		On any other error, return 500 with specific error body
	end note
end group
@enduml