@startuml
!include_many init.puml
note right
	__ $var("client") __
	{
		"id": "$var("stored client id")",
		"channel": "$var("stored channel")",
		"salt": "$var("salt")",
		"secretHash": "$var("secret hash")",
		"description": "$var("description")"
	}
end note
@enduml