@startuml
!include_many init.puml

group #LightPink client credentials validation
	auth -> serv ++ : getBlob("clients", $var("client id") + ".json")
	
	!include_many blob_usage.puml
	
	serv --> auth -- : $var("client")
	!include_many client.puml

	note over auth #Orange
		On blob not found, return 401 with specific error body
		On any other error, return 500 with specific error body
	end note
	
	auth -> auth : verify that $var("stored channel") is null

	note over auth #Orange
		On verification failure, return 401 with specific error body
	end note

	auth -> auth : verify $var("client secret") against $var("salt") and $var("secret hash")

	note over auth #Orange
		On verification failure, return 401 with specific error body
		On any other error, return 500 with specific error body
	end note
end group
@enduml