@startuml
!include_many init.puml

group #LightBlue search for roles
	auth -> repo ++ : find("acquirerId = ?1 and channel = ?2 and clientId = ?3 and merchantId = ?4 and terminalId = ?5", $var("acquirer id"), $var("channel"), $var("client id"), "NA", $var("terminal id"))

	alt roles found
		repo --> auth : $var("roles")
		!include_many roles.puml
	else roles not found
		repo --> auth -- : //not found//

		auth -> repo ++ : find("acquirerId = ?1 and channel = ?2 and clientId = ?3 and merchantId = ?4 and terminalId = ?5", $var("acquirer id"), $var("channel"), $var("client id"), "NA", "NA")
		repo --> auth -- : $var("roles")
		!include_many roles.puml
	end

	note over auth #Orange
		On roles not found, return 401 with specific error body
		On any other error, return 500 with specific error body
	end note
end group
@enduml