group verify client secret
	mil_auth -> mil_auth : verify secret is not expired
		note left
			//<secret expiration unix epoch>// > //<current unix epoch>//
		end note

	note over mil_auth #Orange
		On secret expired, return HTTP 401 (unauthorized) with specific error body.
	end note

	mil_auth -> mil_auth : verify secret matching

	note over mil_auth #Orange
		On secret mismatch, return HTTP 401 (unauthorized) with specific error body.
	end note
end