group build access token payload
	mil_auth -> mil_auth : generate //<access token payload>//
		note right
			__//<access token payload>//__
			{
				"sub": "//<subject id>//",
				"aud": "mil.pagopa.it",
				"iss": "https:////<host name>///mil-auth",
				"iat": //<issue unix epoch>//,
				"exp": //<expiration unix epoch>//,
				"channel": "//<channel>//",
				"groups": [ //<array of roles>// ]
			}
		end note
end