group get roles
	!include_many ../common/get_azure_access_token_for_storage.puml
	
	note left mil_auth
		__header__
		x-ms-version: 2019-07-07
		Authorization: Bearer //<access token for storage account>//
	end note
	
	alt //<channel>// == POS_SERVICE_PROVIDER
		note left mil_auth
			//<service provider id>// = //<subject id>//
		end note
		
		mil_auth -> azure_st ++ : GET //<storage account base url>///pos_service_providers///<service provider id>//.json
	else //<channel>// == PUBLIC_ADMINISTRATION
		note left mil_auth
			//<payee code>// = //<subject id>//
		end note
		
		mil_auth -> azure_st : GET //<storage account base url>///public_administrations///<payee code>//.json
	else //<channel>// == MIL
		note left mil_auth
			//<microservice>// = //<subject id>//
		end note
		
		mil_auth -> azure_st : GET //<storage account base url>///mil_services///<microservice>//.json
	else //<channel>// == SERVER
		note left mil_auth
			//<client id>// = //<subject id>//
		end note
		
		mil_auth -> azure_st : GET //<storage account base url>///servers///<client id>//.json
	end

	azure_st --> mil_auth -- : HTTP 200 (ok)
		note right
			__body__
			{
				"roles": [ 
					//<array of roles>//
				]
			}
		end note

	note over mil_auth #Orange
		On file not found, return HTTP 401 (unauthorized) with specific error body.
		On any other failure, return HTTP 500 (server error) with specific error body. 
	end note
end