group build access token payload
	mil_auth -> mil_auth : generate //<access token payload>//
		note right
			__//<access token payload>//__
			{
				"sub": "//<bank id>// || //<terminal id>//",
				"aud": "mil.pagopa.it",
				"iss": "https:////<host name>///mil-auth",
				"iat": //<issue unix epoch>//,
				"exp": //<expiration unix epoch>//,
				"channel": "ATM",
				"bankId": "//<bank id>//",
				"terminalId": "//<terminal id>//",
				"userCodeToken": "//<token of user code>//",
				"groups": [ //<array of roles>// ]
			}
		end note
end