participant "ATM Layer" as atm

participant "mil-auth" as mil_auth

participant "Azure Active\nDirectory" as azure_ad
participant "Azure Storage\nAccount" as azure_st
participant "Azure Key\nVault" as azure_kv

participant "Personal Data\nVault" as pdv