group protect user code
	mil_auth -> pdv ++ : PUT /tokenizer/v1/tokens
		note left
			__header__
			x-api-key: //<pdv api-key>//
			__body__
			{
				"pii": "//<user code>//"
			}
		end note
	
	pdv --> mil_auth -- :
		note right
		{
			"token": "//<token of user code>//"
		}
		end note
	
	note over mil_auth #Orange
		On any failure, return HTTP 500 (server error) with specific error body. 
	end note
end