name: Build, push and update

on:
  workflow_dispatch:
    inputs:
      skip-unit-test:
        type: boolean
        required: true
        description: Skip unit-test

jobs:
  build_push_update:
    runs-on: ubuntu-22.04

    environment: dev-cd

    permissions:
      id-token: write
      packages: write

    steps:
      #
      # Checkout the source code.
      #
      - name: Checkout the source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      #
      # Setup Java Build Environment.
      #
      - name: Setup Java Build Environment
        uses: pagopa/mil-actions/setup-java-build-env@241c6c17f483229fdd4ac26c6d79d1d65be2659c # 1.1.1
        with:
          gh_user: ${{ secrets.GIT_USER }}
          gh_token: ${{ secrets.GIT_PAT }}

      #
      # Build and push native container image.
      #
      - name: Build and push native container image
        id: build_image
        uses: pagopa/mil-actions/build-push-native-image@241c6c17f483229fdd4ac26c6d79d1d65be2659c # 1.1.1
        with:
          gh_token: ${{ secrets.GIT_PAT }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          release_version: "${GITHUB_REF////_}"
          skip_test: ${{ inputs.skip-unit-test }}

      #
      # Update Container App.
      #
      - name: Update Container App
        shell: bash
        working-directory: src/main/terraform
        env:
          ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
          ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
        run: |
          terraform init -backend-config="env/dev-cd/backend.tfvars" -reconfigure
          terraform apply -var-file="env/dev-cd/terraform.tfvars" -var="mil_auth_image=${{ steps.build_image.outputs.image }}" -auto-approve -lock-timeout=300s
