name: Integration Tests

on:
  workflow_dispatch:

jobs:
  integration_tets:
    runs-on: ubuntu-22.04

    environment: cstar-d-mcshared

    steps:
      #
      # Checkout the source code.
      #
      - name: Checkout the source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      #
      # Setup Java Build Environment.
      #
      - name: Setup Java Build Environment
        uses: pagopa/mil-actions/setup-java-build-env@f782a1b3cdb79afda2c10007ae46b831b31fe640 # 1.1.2
        with:
          gh_user: ${{ secrets.GIT_USER }}
          gh_token: ${{ secrets.GIT_PAT }}

      #
      # Run integration tests.
      #
      - name: Run integration tests
        run: |
          ${{ runner.temp }}/maven/bin/mvn verify \
            -DskipUTs=true \
            -DskipITs=false \
            -Dbase_uri=${{ secrets.IT_BASE_URI }} \
            -Dadmin_client_id=${{ secrets.IT_ADMIN_CLIENT_ID }} \
            -Dadmin_client_secret=${{ secrets.IT_ADMIN_CLIENT_SECRET }} \
            -Dtoken_info_client_id=${{ secrets.IT_TOKEN_INFO_CLIENT_ID }} \
            -Dtoken_info_client_secret=${{ secrets.IT_TOKEN_INFO_CLIENT_SECRET }} \
            -Dtest_username=${{ secrets.IT_TEST_USERNAME }} \
            -Dtest_password=${{ secrets.IT_TEST_PASSWORD }}
