name: Move related JIRA tasks stutus from "code review" to "in progress"

on:
  pull_request_review:
    types: [submitted]

jobs:
  update-jira:
    runs-on: ubuntu-latest

    steps:
      - name: Find JIRA task IDs from PR title
        run: |
          temp=$(echo "${{ github.event.pull_request.title }}" | grep -o '\[[^]]*\]' | sed 's/\[//;s/\]//' | tr -d ' ')
          IFS=$',' read -ra keys <<< "$temp"
          for key in "${keys[@]}"; do
            echo "Key: $key"
          done
